#підключення бібліотек
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import*
#створення елементів інтерфейсу
app = QApplication([])

#Главное окно
my_win = QWidget()
my_win.setWindowTitle("Площа")
my_win.resize(300, 300)
my_win.setStyleSheet("background-color:lightblue;")
question = QLabel("Знайти площу")
question.setStyleSheet("font-size:20px;")
a1 = QLabel("Довжина:")
a1.setStyleSheet("font-size:15px;")
a = QLineEdit()
b1 = QLabel("Висота:")
b1.setStyleSheet("font-size:15px;")
b = QLineEdit()
button = QPushButton("Вичислити")
button.setStyleSheet("font-size:15px;")
line1 = QHBoxLayout()
line1.addWidget(question, alignment= Qt.AlignCenter)
line2 = QHBoxLayout()
line2.addWidget(a1, alignment= Qt.AlignLeft)
line2.addWidget(a, alignment= Qt.AlignCenter)
line3 = QHBoxLayout()
line3.addWidget(b1, alignment= Qt.AlignLeft)
line3.addWidget(b, alignment= Qt.AlignCenter)
line4 = QHBoxLayout()
line4.addWidget(button, alignment= Qt.AlignCenter)
line = QVBoxLayout()
line.addLayout(line1)
line.addLayout(line2)
line.addLayout(line3)
line.addLayout(line4)
my_win.setLayout(line)
def button_OK():
    c = float(a.text())*float(b.text())
    c = str(c)
    win_1 = QMessageBox()
    win_1.setText(c)
    win_1.setStyleSheet("font-size:25px;")
    win_1.exec_()
button.clicked.connect(button_OK)
my_win.show()
app.exec_()
